backend:
  name: github
  repo: TON_GITHUB/NOM_DU_DEPOT
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Articles"
    file: "content/posts.json"
    fields:
      - label: "Articles"
        name: "items"
        widget: "list"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "content", widget: "text" }
